service: service-01-serverless-service

provider:
    name: aws
    runtime: nodejs12.x
    region: ap-south-1

plugins:
    - serverless-offline

functions:
    hello:
        handler: handler.hello
    jobs:
        handler: src/jobs/handler.handler
