service: rest-api

plugins:
  - serverless-offline    # Add this plugin if you are using it.

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev              # Stage can be changed while executing deploy command.
  region: ap-south-1      # Set region.

functions:
  firstGET:
    handler: features/read.firstGET
    events:
      - http:
          path: first_path
          method: get
