service: rest-api

plugins:
  - serverless-offline    # Add this plugin if you are using it.

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev              # Stage can be changed while executing deploy command.
  region: ap-south-1      # Set region.

package:
  include:
    - features/**
    - models/**

functions:
  getTodo:
    handler: features/read.getTodo
    events:
      - http:
          path: todo/{id}
          method: GET

  listTodos:
    handler: features/read.listTodos
    events:
      - http:
          path: todos
          method: GET

  createTodo:
    handler: features/create.createTodo
    events:
      - http:
          path: todo
          method: POST